version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    # links:
    #   - db
    # environment:
    #   - DB_HOST=db
    ports:
      - '3000:3000'
    command: npm start
    # command: nodemon -L server.js
  # db:
  #   image: mongo:3.3.10
